/* =========================================================
   Customer Shopping Behavior Analysis
   Dataset: customer_shopping_behavior
   ========================================================= */


/* Q1. Total revenue generated by gender */
SELECT
    gender,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY gender
ORDER BY total_revenue DESC;


/* Q2. Average spend with vs without discount */
SELECT
    discount_applied,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer_shopping_behavior
GROUP BY discount_applied;


/* Q3. Top 5 products with highest average review rating */
SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating,
    COUNT(*) AS total_reviews
FROM customer_shopping_behavior
GROUP BY item_purchased
HAVING COUNT(*) >= 30
ORDER BY avg_rating DESC
LIMIT 5;


/* Q4. Average spend by shipping type */
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    COUNT(*) AS total_orders
FROM customer_shopping_behavior
GROUP BY shipping_type
ORDER BY avg_spend DESC;


/* Q5. Subscription vs non-subscription spending */
SELECT
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    COUNT(*) AS total_orders
FROM customer_shopping_behavior
GROUP BY subscription_status;


/* Q6. Top discounted items */
SELECT
    item_purchased,
    COUNT(*) AS total_discounted_orders
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY total_discounted_orders DESC
LIMIT 5;


/* Q7. Spending by age group */
SELECT
    age_group,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    COUNT(*) AS total_orders
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY avg_spend DESC;


/* Q8. Top 5 items by revenue within each category */
SELECT
    category,
    item_purchased,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY category, item_purchased
ORDER BY category, total_revenue DESC;


/* Q9. Purchase behavior by frequency */
SELECT
    purchase_frequency_days,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    COUNT(*) AS total_orders
FROM customer_shopping_behavior
GROUP BY purchase_frequency_days
ORDER BY purchase_frequency_days;


/* Q10. Top 5 revenue-generating locations */
SELECT
    location,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    COUNT(*) AS total_orders
FROM customer_shopping_behavior
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 5;
